# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Onionpipe < Formula
  desc ""
  homepage ""
  version "1.1.11"

  depends_on "tor"

  on_macos do
    url "https://github.com/cmars/onionpipe/releases/download/v1.1.11/onionpipe_1.1.11_darwin_amd64.tar.gz"
    sha256 "512e7d68828e736a9eff67f1b56da4c75d8fc218cde4aab4d817645d4a40b641"

    def install
      bin.install "onionpipe"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Onionpipe
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cmars/onionpipe/releases/download/v1.1.11/onionpipe_1.1.11_linux_amd64.tar.gz"
        sha256 "83cac4fec1e0be06329402a93265d6ff2fe653e94de43288c3b0d6927e760182"

        def install
          bin.install "onionpipe"
        end
      end
    end
  end
end
