# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oniongrok < Formula
  desc ""
  homepage ""
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cmars/oniongrok/releases/download/v0.3.0/oniongrok_0.3.0_darwin_amd64.tar.gz"
      sha256 "bfb544c8166a2d35b5b2bab181412996edd6dc4e64dca06af443c1caa8197b04"

      def install
        bin.install "oniongrok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cmars/oniongrok/releases/download/v0.3.0/oniongrok_0.3.0_linux_amd64.tar.gz"
      sha256 "b19572f861e4405e2958a3725e566d7ae33f6456e34fe221f5d15cad7dd4e4a9"

      def install
        bin.install "oniongrok"
      end
    end
  end

  depends_on "tor"
end
