# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oniongrok < Formula
  desc ""
  homepage ""
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cmars/oniongrok/releases/download/v0.4.0/oniongrok_0.4.0_darwin_amd64.tar.gz"
      sha256 "ddbfd892a7a6301d8fc9987355e4b5e68dbc8afea931484a7692a1a631886673"

      def install
        bin.install "oniongrok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cmars/oniongrok/releases/download/v0.4.0/oniongrok_0.4.0_linux_amd64.tar.gz"
      sha256 "e7d1e30a2dd55c5078691ec7adb5f283c49cf3448ee1e5d627fec435004f614b"

      def install
        bin.install "oniongrok"
      end
    end
  end

  depends_on "tor"
end
