# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oniongrok < Formula
  desc ""
  homepage ""
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cmars/oniongrok/releases/download/v0.1.2/oniongrok_0.1.2_darwin_amd64.tar.gz"
      sha256 "7d777291f7270e3fdb6d2c4a5a6aca1d8ed6deda3a8c24d103907be39b580329"

      def install
        bin.install "oniongrok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cmars/oniongrok/releases/download/v0.1.2/oniongrok_0.1.2_linux_amd64.tar.gz"
      sha256 "11c17d6cea68ee1ba6514bce6143a6a9576907ba9dae5d46cbdc1fe1f8931111"

      def install
        bin.install "oniongrok"
      end
    end
  end
end
