# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Onionpipe < Formula
  desc ""
  homepage ""
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cmars/onionpipe/releases/download/v1.0.0/onionpipe_1.0.0_darwin_amd64.tar.gz"
      sha256 "bb13087c81ea030c573e5f927ab116880f500544a04014c3c95ef380203eabd6"

      def install
        bin.install "onionpipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cmars/onionpipe/releases/download/v1.0.0/onionpipe_1.0.0_linux_amd64.tar.gz"
      sha256 "dda9fbc0854e469d3ec408bcbd0d406f228fe970304f86e8ea5e702473c62d01"

      def install
        bin.install "onionpipe"
      end
    end
  end

  depends_on "tor"
end
